version: 0.2


phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Loggin to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891377055161.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=891377055161.dkr.ecr.us-east-1.amazonaws.com/devops/tripmgmtdemo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - chmod 755 ./gradlew
      - ./gradlew clean
      - ./gradlew bootWar -Pprod -Pwar
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
